// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vaqvegsylvcbfoxytnme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhcXZlZ3N5bHZjYmZveHl0bm1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NTIwMDAsImV4cCI6MjA2NTQyODAwMH0.FQcdZZPjja9whS4YT8q47KxUXwx85fc_LTvryH2iZQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);